app = 'chatifiy-3'
primary_region = 'lhr'

[build]
  dockerfile = "Dockerfile"
  [build.args]
    GO_VERSION = '1.23.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
